trunk-version = ">=0.20.0"
target = "index.html"
dist = "dist"
public-url = "/"

[serve]
port = 8080
hostname = "0.0.0.0"
open = false
watch-interval = 500

[build]
release = false
public-dir = "src/assets"
